### PR TITLE
Add note about recovery to changelog/update version

### PR DESCRIPTION
**Pull request by DanTup**
@bwilkerson the previous PR didn't update the changelog. I've updated it here and bumped the version, although I'm not sure if I've done this correctly for this repo.

### CODE REVIEW

**Review by bwilkerson — APPROVED** [review]
I believe that this is correct. I'll wait a bit to merge it in case Jake wants to comment.

**Comment by DanTup** [comment]
@jakemac53 @bwilkerson ping! :)

It'd be good to roll this into the analyzer too to be able to land package-name-completion, although I'm not sure if there's a process for that (or if jumping up to a null-safe version of yaml adds additional complications).

**Comment by jakemac53** [comment]
The null same yaml should already be in the SDK since the analyzer has migrated - so no issues there afaik.

This looks sane to me assuming this is non-breaking which it sounds like it is.

**Comment by bwilkerson** [comment]
The process for rolling a new version into the SDK consists of publishing this package and then updating the DEPS file (in the root of the sdk repo). I probably don't have the necessary permissions to publish it.

**Comment by bwilkerson** [comment]
Yes, these changes are non-breaking. We've added an optional named parameter to a small number of public functions/methods to allow "recovery mode" to be requested. The behavior for existing clients won't change unless they start passing in the extra argument.

**Comment by bwilkerson** [comment]
@jakemac53 Could you publish a new version? Danny or I can then pull it into the SDK.

**Comment by jakemac53** [comment]
I can publish it yes

**Comment by DanTup** [comment]
Thanks! 👍

**Pull request merged**
