### PR TITLE
solved emoji problem

### PR DESCRIPTION
**Pull request by c9addy**
Solved emoji problem.
Now by new example.dart we can print out emoji from our yaml file.

### CODE REVIEW

**Comment by aditya18378** [comment]
Solved emoji problem.
Now by new example.dart we can print out emoji from our yaml file.

**Comment by aditya18378** [comment]
@googlebot I fixed it

**Comment by aditya18378** [comment]
@googlebot I fixed it.

**Comment by aditya18378** [comment]
@googlebot I fixed it.

**Comment by athomas** [comment]
Note, the CLA bot hasn't authorized you because it can't connect he committer email to your github account. Try the troubleshooting instructions here to get your PRs accepted: https://opensource.google/docs/cla/#wrong-email

**Comment by littoy** [comment]
why not merged

**Comment by athomas** [comment]
@littoy The author does not pass the CLA check, the Dart team is not even allowed to look at the PR until that check has passed.

**Comment by kevmoo** [comment]
This PR does ~nothing. It changes no behavior, etc. Closing out.

**Pull request closed without merging**
