### PR TITLE
Example

### PR DESCRIPTION
**Pull request by c9addy**
Created a project inside a example folder with main.dart using yaml and path to print data of yaml file (pubspec.yaml in this case).

### CODE REVIEW

**Comment by aditya18378** [comment]
Updated example.dart file

**Comment by aditya18378** [comment]
Example is for parsing without providing actual yaml file, I guess thats
why it need to be updated.
Regards Aditya Singh

**Comment by iapicca** [comment]
@c9addy
https://github.com/dart-lang/yaml/issues/92

**Comment by sigurdm** [comment]
This removes the copyright header and is not very interesting.

**Pull request closed without merging**
